spring:
  application:
    name: MELI Mutanst Analyzer DNA
  profiles:
    active: ${MELI_MUTANTS_SERVER_PROFILE:dev}
  banner:
    location: classpath:banner.txt

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${MELI_MUTANTS_SERVER_CONTEXT_PATH:/}