# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Meli Test Build Workflow

on: [push, pull_request]

jobs:
  build:
    name: Gradle build Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean packages
        uses: ./.github/actions/packages
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN }}
          owner: ${{ github.actor }}
          repository: codehuntersio-java-commons-support
          versions: 2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Build with gradle
        run: gradle --build-cache build -x test
      - name: Publish to gitHub packages
        run: gradle publish
        env:
          GH_PACKAGES_USERNAME: ${{ github.actor }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
